apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-route
  namespace: monitoring
spec:
  parentRefs:
  - name: main-gw
    namespace: gateway
  hostnames:
  - "grafana.local"
  rules:
  - backendRefs:
    - name: monitoring-grafana # points to a Service (kubectl -n monitoring get svc monitoring-grafana)
      port: 80