apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: logging
spec:
  interval: 10m
  chart:
    spec:
      chart: loki
      version: "6.49.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    createNamespace: false
  upgrade:
    cleanupOnFail: true
  valuesFrom:
    - kind: ConfigMap
      name: loki-values
      valuesKey: values.yaml
