apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: java-demo-api
  namespace: java-demo
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/java-demo-api
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    createNamespace: false
  upgrade:
    cleanupOnFail: true
  values:
    service:
      port: 9000
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 75
  valuesFrom:
    - kind: ConfigMap
      name: java-demo-api-image
      valuesKey: values-image.yaml
