apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blackbox-exporter
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      version: ">=8.0.0 <9.0.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1h
  values:
    service:
      type: ClusterIP

    config:
      modules:
        http_2xx:
          prober: http
          timeout: 5s
          http:
            method: GET
            follow_redirects: true
            preferred_ip_protocol: ip4

        # This module is what adds: Host: api.local
        http_java_demo_api_health:
          prober: http
          timeout: 10s
          http:
            method: GET
            headers:
              Host: api.local
            follow_redirects: true
            preferred_ip_protocol: ip4
