apiVersion: v1
kind: Service
metadata:
  name: envoy-proxy-metrics
  namespace: envoy-gateway-system
  labels:
    app.kubernetes.io/name: envoy
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: envoy
  ports:
    - name: metrics
      port: 19001
      targetPort: 19001
      protocol: TCP
